import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'playwright');
const browser = await chromium.launch({ headless: true, channel: 'msedge' });
const errors = [];
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
page.on('pageerror', error => errors.push(error.message));
page.on('response', response => { if (response.status() >= 400) errors.push(`${response.status()} ${response.url()}`); });
await page.goto('http://localhost:3000', { waitUntil: 'networkidle' });
await page.evaluate(() => document.fonts.ready);
await page.locator('img').evaluateAll(images => Promise.all(images.map(image => { image.loading = 'eager'; return image.decode(); })));
assert.equal(await page.locator('h1').count(), 1);
assert(await page.evaluate(() => document.fonts.check('16px Cabin')));
assert.deepEqual(await page.locator('img').evaluateAll(images => images.filter(image => !image.complete || !image.naturalWidth).map(image => image.src)), []);
assert.deepEqual(await page.locator('a[href^="#"]').evaluateAll(links => links.map(link => link.getAttribute('href')).filter(href => href !== '#' && !document.getElementById(href.slice(1)))), []);
await page.screenshot({ path: 'preview-desktop-full.png', fullPage: true });
await page.locator('[data-service="Mobile applications"]').click();
assert(await page.locator('input[name="service"][value="Mobile applications"]').isChecked());
await page.locator('#contact-form button').click();
assert.equal(await page.locator('input[name="firstName"]').evaluate(input => input.validity.valueMissing), true);
await page.locator('input[name="firstName"]').fill('Alex');
await page.locator('input[name="lastName"]').fill('Morgan');
await page.locator('#contact-form input[name="email"]').fill('alex@example.com');
await page.locator('textarea').fill('We would like a mobile app for our customer portal.');
await page.evaluate(() => { window.openEmail = (subject, body) => { window.testEmail = { subject, body }; }; });
await page.locator('#contact-form button').click();
const draft = await page.evaluate(() => window.testEmail);
assert(draft.subject.includes('Mobile applications'));
assert(draft.body.includes('alex@example.com') && draft.body.includes('customer portal'));
assert((await page.locator('#form-status').textContent()).includes('email draft'));
await page.locator('#updates-email').fill('news@example.com');
await page.locator('#updates-form button').click();
assert((await page.evaluate(() => window.testEmail.body)).includes('news@example.com'));
for (const width of [320, 375, 390, 768, 1024, 1440, 1920]) {
  await page.setViewportSize({ width, height: 900 });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `Horizontal overflow at ${width}`);
}
await page.setViewportSize({ width: 390, height: 844 });
await page.goto('http://localhost:3000', { waitUntil: 'networkidle' });
await page.locator('img').evaluateAll(images => Promise.all(images.map(image => { image.loading = 'eager'; return image.decode(); })));
await page.locator('.menu-toggle').click();
assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'), 'true');
await page.keyboard.press('Escape');
assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'), 'false');
await page.locator('.menu-toggle').click();
await page.locator('#navigation a[href="#services"]').click();
assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'), 'false');
await page.evaluate(() => scrollTo(0, 0));
await page.screenshot({ path: 'preview-mobile.png', fullPage: true });
await page.locator('#contact').scrollIntoViewIfNeeded();
await page.screenshot({ path: 'preview-mobile-contact.png' });
assert.equal(await page.locator('.digital-core').evaluate(element => getComputedStyle(element).animationName), 'none');
await page.setViewportSize({ width: 1440, height: 1000 });
await page.locator('#about').scrollIntoViewIfNeeded();
await page.screenshot({ path: 'preview-about.png' });
await page.locator('#contact').scrollIntoViewIfNeeded();
await page.screenshot({ path: 'preview-contact.png' });
await page.close();
const noJS = await browser.newPage({ javaScriptEnabled: false, viewport: { width: 390, height: 844 } });
await noJS.goto('http://localhost:3000');
assert(await noJS.locator('#services').isVisible());
await browser.close();
assert.deepEqual(errors, []);
console.log('PASS: seven responsive widths; images and fonts; anchor targets; service selection; form validation and draft contents; mobile menu; reduced motion; no browser errors.');
